# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: mnist.yaml # choose the datamodule for evaluation
  - model: mnist.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  # - experiment: face_recognition/ssl/pml_id_net_fine_tuned_sim_clr_backbone_face_body.yaml
  - experiment: face_recognition/ssl/pml_id_net_fine_tuned_sim_clr_backbone_face_body

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

ckpt_path: <add-yours>
