_target_: src.datamodules.triplet_autoencoder_datamodule.TripletAutoencoderDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
folder_dir: ${data_dir}/icf_dass_faces
batch_size: 128
train_val_test_split: [0.92, 0.96, 1]
num_workers: 0
pin_memory: False